inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

AllCops:
  Exclude:
    - 'test/**/*' # test ディレクトリ内の全てのファイルを除外
    - 'test/**/*.rb' # test フォルダ内の Ruby ファイルも除外


