inherit_from: .rubocop_todo.yml
<<<<<<< HEAD

AllCops:
  NewCops: enable

Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true
=======
>>>>>>> d83ee46f6a74ffc7cff9ee3271ce5b3b2faeafbd
