version: '3'
services:
  db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    command: bundle exec rails server -p 3000 -e development
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint:
      - "/usr/bin/wait-for-it.sh"
      - "db:5432"
      - "--"
      - "bash"
      - "-c"
      - "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  
  chrome:
    image: seleniarm/standalone-chromium:121.0 
    ports:
      - 4444:4444

volumes:
  postgres_data:
  bundle_data:
  node_modules:
